### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by dmarychev** [FredieJackson/WaterSimulation#1]
Required assets are missing from the sources tree. https://github.com/FredieJackson/WaterSimulation/blob/a245e4b16d125db3c26b465c15bb15c3c20947cf/GameEngine/Game.cpp#L70

Also please get rid of files produced by MSVS build (bin/, lib/ etc).

D

**Comment by vcstk** [comment]
Ok, I'll fix it, thanks.

**Comment by vcstk** [comment]
done
